name: Generate binary and hex outputs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Install AVR toolchain
      run: |
        sudo apt-get update
        sudo apt-get install gcc-avr binutils-avr avr-libc
        
    - name: Build blinky_test
      run: |
        cd blinky_test && make
        
    - name: Build bootloader
      run: |
        cd bootloader && make
        
    - name: Upload blinky_test build output
      uses: actions/upload-artifact@master
      with:
        name: blinky_test
        path: |
          blinky_test/build/program.bin
          blinky_test/build/program.hex
          
    - name: Upload bootloader build output
      uses: actions/upload-artifact@master
      with:
        name: bootloader
        path: |
          bootloader/build/program.bin
          bootloader/build/program.hex
